---
# Installs XOS on Cloudlab's OpenStack profile systems

- hosts: cloudlab

  vars:
    xos_repo_url: "https://github.com/opencord/xos"
    xos_repo_dest: "~/xos"
    xos_repo_branch: "master"
    xos_configuration: "devel"
    xos_container_rebuild: true

  roles:
    - { role: common-prep, become: yes }
    - xos-install

