---
# Tests single node cord-pod XOS configuration

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - vars/cord_defaults.yml
        - vars/cord.yml
        - vars/example_keystone.yml

- name: Run platform checks
  hosts: head
  become: no
  roles:
    - platform-check

- name: Create test client
  hosts: head
  become: yes
  roles:
    - maas-test-client-install

- name: Run post-deploy tests
  hosts: head
  become: no
  roles:
    - test-vsg
    - test-exampleservice
