---
#file: roles/dns-unbound/tasks/main.yml

- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

# Debian specific installation
- include: unbound-Debian.yml
  when: ansible_os_family == 'Debian'

- name: create unbound.conf from template
  template:
    src=unbound.conf.j2
    dest={{ unbound_conf }}
    mode=0644 owner=root group={{ unbound_group }}
    # validate='unbound-checkconf %s' - can't use, checks path, not just config.
  notify:
   - restart-unbound

