---
# compute-node-enable/tasks/main.yml

- name: Load TOSCA to add OpenStack compute nodes
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} {{ cord_profile_dir }}/{{ item }}"
  with_items:
    - openstack.yaml
    - openstack-compute.yaml
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Pause to work around race in VTN or ONOS synchronizers
  pause:
    seconds: 20

- name: Load TOSCA to enable VTN on OpenStack compute nodes
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} {{ cord_profile_dir }}/{{ item }}"
  with_items:
    - vtn-service.yaml
    - openstack-compute-vtn.yaml
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

