---
# simulate-fabric/defaults/main.yml

simfabric_bridges:
  - name: databr
    addresses:
      - "10.168.0.1/24"
      - "10.168.1.1/24"
    interfaces:
      - veth0

simfabric_links:
  - name: veth
    mac: "02:42:0a:a8:00:01"

simfabric_interfaces:
  - veth0
  - veth1

simfabric_iptables:
  - table: nat
    chain: POSTROUTING
    source: "10.168.0.0/16"
    dest: "! 10.168.0.0/16"
    jump: MASQUERADE

simfabric_sysctl:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv4.conf.eth0.send_redirects
    value: 0
  - name: net.ipv4.conf.databr.send_redirects
    value: 0
