---
# xos-start/tasks/main.yml

- name: Build XOS containers
  command: ansible xos-1 -u ubuntu -m shell \
    -a "bash -c \"cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make local_containers |& tee xos-build.out\""

- name: Onboard services and start XOS
  command: ansible xos-1 -u ubuntu -m shell \
    -a "bash -c \"cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make xos |& tee xos-onboard.out\""

- name: Pause to let XOS initialize
  pause: seconds=120

- name: Initial VTN configuration
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make vtn"

- name: Initial fabric configuration
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make fabric"

- name: Pause to let ONOS initialize
  pause: seconds=20

- name: Configure CORD services
  command: ansible xos-1 -u ubuntu -m shell \
    -a "cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make cord"
