---
# prereqs-common/defaults/main.yml

min_memtotal_mb: 48000
min_processor_vcpus: 12

kvm_check: true

dns_check_domain: wiki.opencord.org
dns_check_ipv4: 52.9.82.207

# obtained from: https://www.iana.org/domains/root/servers
dns_roots:
  - 192.5.5.241
  - 193.0.14.129
  - 198.41.0.4
  - 199.7.91.13

http_dl_url: "http://cord.staging.wpengine.com/wp-content/uploads/2016/07/cord-tm-logo.png"
http_dl_cksum: "sha256:9a69c741a4bb609ad7e49bd0fd335a95db2e66dc0d72866569e11385df9dcc28"

https_dl_url: "https://jenkins.opencord.org/static/8d0f081d/images/headshot.png"
https_dl_cksum: "sha256:690e82fb98ffb2b4b232d9b9cf9cc52eb7972e56a84902f6d1150b75456058c6"

