---
# xos-config/tasks/main.yml

- name: Bootstrap XOS database - create site, deployment, admin user
  command: "python /opt/xos/tosca/run.py none /opt/cord_profile/{{ item }}"
  with_items:
    - "fixtures.yaml"
    - "deployment.yaml"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Configure XOS with OpenStack config
  when: use_openstack
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/{{ item }}"
  with_items:
    - openstack.yaml
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

- name: Configure XOS with profile specific TOSCA
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/{{ item }}"
  with_items: "{{ xos_tosca_config_templates }}"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

