---
# xos-docker-images/defaults/main.yml

cord_dir: "{{ ansible_user_dir + '/cord' }}"

build_xos_base_image: False
build_xos_test_image: False

deploy_docker_registry: "localhost:5000"
deploy_docker_tag: "latest"

push_xos_base_image: False
push_xos_image: False

